### ISSUE TITLE
Seznámení s Maven

### ISSUE THREAD

**Issue by bombic94** [Pumprdlici/hadej_cislo#1]
hrál jsem si s tim celej víkend, nikam jsem nepokročil, je v těch knihovnách strašnej bordel, akorát jsem toho hodně rozbil, takže jestli se někomu povede překonvertovat projekt do Mavenu, má u mě pivo a půl princezny

**Comment by Sedmikras** [comment]
Dneska sem začal a zjistil, že už je hotovo. S křížkem po funuse připisuju si jednu hodinu do pomyslného deníčku.

**Comment by bombic94** [comment]
Princeznu si nechte celou, povedlo se mi to rozběhat :)
V nově založeném branchi converting to Maven01 (nově nastaven jako defaultní) je oproti původnímu projektu změna, přidán soubor pom.xml, a předělána složka lib.
Postup pro Eclipse: po nainstalování mavenu a pluginu pro eclipse překonvertujte projekt guess_the_number do Maven projektu, do kořenové složky projektu nahrát soubor pom.xml a novou složku lib(přepsat). V Eclipsu v Properties projektu odstranit závislosti na všech externích knihovnách, nechat pouze JRE a Maven Dependencies.
Mělo by to šlapat

**Comment by bombic94** [comment]
PS: z nějakého důvodu se mi poprvé při konvertování projektu nastavil Compiler na 1.5, pak vám nic nepoběží :D tak nastavte popřípadě na 1.8

**Comment by Sedmikras** [comment]
Jo v IDEE taky dá na 1.5 hledání je docela opruzácký. Zkusim to nahodit už jako maven project.

**Comment by bombic94** [comment]
Tak aby těch problémů nebylo málo :) při konverzi do Mavenu asi pořád ještě nechtějí uplně kamarádit ty externí knihovny... chybu vyhodí použití klasifikátoru MLP a SVM, závisí právě na těch externích knihovnách... zkusím s tím něco udělat at to běhá, popřípadě můžem na konci říct zadavateli že jsme holt vyměnili kus za kus :)

**Comment by mirha2009** [comment]
když jsem si znovu projížděl ten pom.xml, tak jsem nenašel zahrnutou následující závislost, tak by to možná mohl být ten kámen úrazu.
- https://github.com/bombic94/guess_the_number/blob/master/lib/lib/MPERPs.jar

Pokud to stejně nebude fungovat, tak je další možný problém ve verzích jarů. Nelze předpokládat, že jsou zpětně kompatibilní s nižšími verzemi. 
Zkuste se k tomu vyjádřit a já se to když tak pokusím nerozházet :).

**Comment by mirha2009** [comment]
pom.xml opraven.
přidal jsem MPERPs.jar a teď už to funguje jako před tím
