### ISSUE TITLE
Rozběhat DeepLearning4J

### ISSUE THREAD

**Issue by bombic94** [Pumprdlici/hadej_cislo#3]
zatím pláču

**Comment by Sedmikras** [comment]
Naimportováno. Teď zjistit jak implementovat klasifikátor. Postup bude následující :
- vytvořit s tim, že implementujeme rozhraní 
- ?
- profit

**Comment by mirha2009** [comment]
zdroják z deeplearning
http://deeplearning4j.org/iris-flower-dataset-tutorial.html

**Comment by bombic94** [comment]
po včerejší aktualizaci mi to hází nějakej výmysl at si nainstaluju BLAS pro správné fungování nd4j. Opravdu se snažim ale zatim bez úspěchu. Pochybuju ovšem že to vyřeší náš problém s nekompatibilností DataSetů. Co novýho u Vás?

**Comment by Sedmikras** [comment]
Jo taky sem instaloval openBLAS - http://nd4j.org/getstarted.html. Je to docela velkej sranec. Trochu mi sere, že máme kvadrilion knihoven a bez nich to nejde a musíš mít staženo tisícero software aby ti to fungovalo. Dneska pokusim odstranit další error - 
**Exception in thread "main" java.lang.IllegalStateException: Column of left array 48 != rows of right 4 or rows of left array 120 != columns of right 3***

**Comment by bombic94** [comment]
i bez instalace openBLAS se mi povedlo natrénovat klasifikátor, vyhodil lehce odlišné výsledky (malé odchylky ve weights), procento úspěšnosti bylo taky 50%, 35 true negatives, 35 false negatives

**Comment by bombic94** [comment]
povedlo se změnit ukládání a načítání DBN klasifikátoru v závislosti na Feature Extraction. Přidány soubory .classifier a .bin s uloženou konfigurací.

**Comment by bombic94** [comment]
implementován a natrénován StackedDenoisingAutoencoder.
stejně jako v DBN chybí parametrický konstruktor a metoda classify.
zbytek je téměř stejný až na část metody train...
do složky se zdrojovými kódy nahrány dva soubory:
DBNClassifier.java - původní DeepLearning.java, pouze přejmenován aby se dal používat jako klasifikátor
SDAClassifier.java - nový StackedDenoisingAutoencoder
do složky s natrénovanými classifier soubory nahrány vytrénované klasifikátory s růzými FeatureExtraction.
Snad se v tom dá vyznat.

**Comment by bombic94** [comment]
Aktuální úkoly: 1) doplnit metodu classify, inspirovat se nejvíce asi v MLP, i v ostatních klasifikátorech, na netu.
2) Konstruktor bych nechal konstruktorem, s parametrama si můžeme hrát až to bude fungovat. Teprve pak bych napojil GUI a našel parametry které by si mohl uživatel nastavit.
3) Nevím jak se tvoří txt soubory pomocí kterých načítáme klasifikátor. Říkal to Vařeka? Popřípadě se zeptat co nejdříve.
4) Začít konečně klasifikovat data :)

**Comment by bombic94** [comment]
Rozběháno spouštění DBN a SDA klasifikátorů přes výběr .txt a .classifier souborů. Zatím funguje bez parametrů. Aplikace s tím běží, zatím neklasifikuje :) po doladění metody classify by už měla klasifikace bez problému proběhnout.
Soubory txt jsou uloženy ve složce data/test_classifiers_and_settings
Nutno používat novou třídu z GUI MainFrame.java

**Comment by Sedmikras** [comment]
Klasifikátory klasifikují, ale problém je tu ten, že nenačítáme klasifikátor v GUI. Jenom se "otevře". Tudíž model=null a ten těžko může vyhazovat output. Vůbec netušim, kde je to v kódu - takže bych byl rád, kdyby ste to někdo udělal. Nahodim funkční prototypy klasifikátorů a v metodě classify() zakomentuju místo, kde už musí bejt model inicializovanej(to ani nemusim snad)

**Comment by bombic94** [comment]
je to nahozený, ale pro různé extrakce příznaků hází různé výjimky. (rozměry polí) Jediná funkční je WaveletTransformFE, MatchingPursuit a FilterAndSubsampling nekamarádí. Někde bude chybička v nastavování velikosti pole

**Comment by bombic94** [comment]
Zatím funguje klasifikace podle klasifikátorů s označením 18, 20, 21. Ostatní zatím hází chybu

**Comment by bombic94** [comment]
Nahrány nové verze několika tříd ve složce classification a ve složce gui. V DBN a SDA trochu upraven kód aby to už malinko vypadalo a dávalo smysl, ostatní třídy pouze implementují novou metodu loadConf. Stáhněte si všechno nový prosim, snad to funguje :)

**Comment by bombic94** [comment]
založen nový branch finishing-classifying.
Už se blížíme do finiše. Nějakým způsobem (neptejte se mě jak) se mi podařilo rozchodit všechny klasifikátory. Funkční soubory jsou uloženy v data/test_classifiers_and_settings.
O funkčnosti a kvalitě klasifikace se dá diskutovat (je to uplně nahovno), každopádně jsem zkusil klasifikovat jedny data všema klasifikátorama a žádná sláva to není nikde, takže myslím že už se to dá vzít jako splněný projekt.
Prosím stáhněte si všechny dnes upravené třídy a soubory a dejte vědět jestli to funguje i Vám nebo jenom mně a budu muset s projektem odevzdat i počítač :)

**Comment by Sedmikras** [comment]
Uzavřeno. Dále probíhá ladění-
