### ISSUE TITLE
Sejít se s Vařekou

### ISSUE THREAD

**Issue by bombic94** [Pumprdlici/hadej_cislo#4]
nutno dát dohromady schůzku: já tu příští týden zase nejsem, takže by bylo vhodný to stihnout tento týden, nebo popřípadě pujdete beze mne a budete hodně poslouchat a zapisovat si :)
body:
Třída DeepLearning.java (je to DeepBeliefNetworks):
1. metoda save, metoda load - jak si to představuje, soubory txt, classifier
2. konstruktor, implicitní + s parametry
3. co dál je třeba implementovat, jak a proč
4. jaký network + classifier to implicitně využívá?

Třída StackedDenoisingAutoencoder:
1. zatím vůbec neimplementováno
2. pláčem a pláčem

**Comment by bombic94** [comment]
Ahoj, prosím, až budete mít chvilku, sepište jak to dnes proběhlo, popřípadě co je vhodné tento týden udělat a jestli jste se hned domluvili na příště :)

**Comment by mirha2009** [comment]
Odpovědi na otázky ze schůzky
1) Metodu load a save máme nechat tak jak jí oni mají defalutně, akorát máme přejmenovat jason na classifier a to je vše.
2)Konstruktory by to prý chtělo oba
3)zatím máme nechat klidně ty dosavadní 3 vrstvy
-problém, proč nám to padlo, je to že jsme vůbec neřešili dataset a nechali tam ten původní iris, který mají v examples
-takže aby to běhalo musíme vytvořit dataset, který je popsaný na stránkách deeplearning
-všude kde pracujeme s epochami, tak z nich musíme dostat feature vektor, jinak to nebude fungovat
-tuto je hlavní úkol našeho projektu

**Comment by mirha2009** [comment]
další schůzka je předběžně naplánovaná na příští pondělí taktéž od 10:20
