### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by bombic94** [Pumprdlici/hadej_cislo#5]
vidím že Míra se do toho trochu pustil, děkuju :)

po zakomponování klasifikátorů do programu zbývá napojit na GUI

**Comment by Sedmikras** [comment]
Prosim o vyřešení inicializace modelu z texťáku. díky.

**Comment by bombic94** [comment]
inicializace funguje, pro DBN bez problémů, SDA by ještě chtělo malinko doladit :)

**Comment by bombic94** [comment]
Všechno funkční
