### ISSUE TITLE
Zbývající věci na dodělání

### ISSUE THREAD

**Issue by bombic94** [Pumprdlici/hadej_cislo#7]
Na příští týden:
1) Je třeba nějak upravit kód a kvalitněji okomentovat SDA a DBN abychom to mohli ukázat Moučkovi.
2) Pro Vařeku: 
- Protokol o testování?? Nebyl jsem u toho když jste to řešili takže nevím co to má obnášet a zahrnovat, popřípadě jestli už se s tím dá začít.
- Dokument o předání mám připravenej, snad bude co předávat :)
- Říkal že po nás bude chtít něco dalšího?

3) V pondělí 10:20 asi zase schůzka tak mu předvedem co máme a já se ho budu muset zeptat jestli nám to uzná aspoň za míň bodů nebo vůbec a mám rovnou někam skočit :)
4) Pouze pro Sedmikráse: Na UIR bychom k tomu asi měli mít i nějakou dokumentaci, zatím jsem na to vůbec nekoukal, ale plánuju tam přeložit akorát tutoriál z deeplearning4j. Nějakej nápad? :D

**Comment by bombic94** [comment]
Nahrány nové verze několika tříd. Omlouvám se, že jsem toho předělal tolik, bojoval jsem s ukládáním a načítáním tak, aby to trochu fungovalo nejlépe v rámci již vytvořeného programu. Předtím jsem musel pozměnit i interface a adaptér, teď se mi to povedlo pozměnit tak aby to nebylo třeba a bylo to funkční s původní verzí.
Co se týče parametrů pro naše klasifikátory, napadá mne akorát nechat na uživateli určit počet iterací. Defaultně bych nechal 10, s větším počtem by se měl proces urychlit ale uplně přesně jsem to nepochopil. Ani to asi nemá vliv na výsledky.
V DBN a SDA je přidáno milion komentářů. Chybí okomentovat save a load, teď už mi to moc nebaví a jdu si učit uir. Možná se k tomu dostanu ještě večer.

**Comment by bombic94** [comment]
Nahrány nové verze SDA a DBN (přidán parametrický konstruktor, nastavení iterací).
V závislosti na tom upraveno GUI (nahrány nové verze dvou tříd), přidán JSpinner s volbou iterací.
Nahrány nové txt soubory s konfigurací, je tam přidaná poslední řádka s defaultním nastavením 10 iterací.

**Comment by bombic94** [comment]
nahrány nové verze všech .classifier, .txt a .bin souborů, jsou natrénovány z poslední verze sítí SDA a DBN. Fungují pro klasifikaci jednotlivých vybraných eeg souborů, nefungují pro "test all datasets", s tím si nevím rady. Alespoň už ukazují nějaké kvalitnější výsledky, po dotestování tříd a nalezení ideálních parametrů se vytrénují finální verze, takže jestli si s tím nechcete hrát, asi není úplně nutno zatím stahovat.

**Comment by bombic94** [comment]
opět a snad už naposledy. nahrány nové verze všech .classifier, .txt a .bin souborů (více v Issue ladění). Upraven kód v GUI (ChangeClassifierFrame) a upraveny třídy DBN a SDA. Postahujte prosím a zjistěte jestli vám to funguje jak má.

**Comment by bombic94** [comment]
Je třeba do středy dopsat ty komentáře. Komu se chce? :) Je to už skoro hotový, chybí pár informací ke konstantám, proměnným a možná připsat něco k tomu jako nahráváme ty data

**Comment by Sedmikras** [comment]
Nechce se mi, ale zítra si na to vyhradim tak 2 hodiny. Spíš než komentáře, ale budu přejmenovávat proměnný a podobný srandy.

**Comment by bombic94** [comment]
konec hotovo
