### ISSUE TITLE
Testování a ladění

### ISSUE THREAD

**Issue by Sedmikras** [Pumprdlici/hadej_cislo#8]
Domluvit se se zadavatelem a začít ladit a testovat. Chtělo by to ještě schůzku kde mu ukázat že sme splnili 2. část a přejít do třetí definitivní fáze.

Nejlépe to stihnout do konce semestru(hahaha).

**Comment by bombic94** [comment]
Otestován případ: klasifikátor DBN, extrakce příznaků DWT - maximální úspěšnost 52% při počtu neuronů 40 a počtu iterací 8947.
Do večera hodím DBN s MP, naházejte sem prosím co kdo máte, ať to máme ucelený a můžem to hodit do protokolu o testování

**Comment by Sedmikras** [comment]
Optimalizace : 
SDA FS(68%) - 816 iterací, 25neuronů
SDA DWT(72%) - 959iterací, 39neuronů
SDA MP(76%) - 439iterací, 21neuronů
Stacked Denoising Autoencoder s MatchingPursuit feature extraction se tedy stává výhercem celé soutěže. Gratulujeme k úspěchu

**Comment by Sedmikras** [comment]
PS : pro zajímavost při optimalizaci je průměr SDA MP 66% což je o procento víc, než je úspěšnost človeka.

**Comment by Sedmikras** [comment]
DBN FS(53%) - 9418iterací, 42 neuronů.

**Comment by bombic94** [comment]
klasifikátor DBN, extrakce příznaků MP, maximální úspěšnost 65% při počtu neuronů 24 a počtu iterací 2766
Tímto by to bylo všechno, jdu začít natrénovat, iterací necham defaultně 1000, neurony podle nejlepší úspěšnosti.
Může se sepsat protokol :)

**Comment by mirha2009** [comment]
myslím, že by bylo dobré si zaznamenat i parametry algoritmů pro extrakci příznaků, aby to mělo nějakou formu. Dále nějaké nevhodné konfigurace, které hází žalostná procenta, aby byl vidět rozdíl při nastavení parametrů. Dále se chci zeptat, jestli je vhodné jako vzorová data brát to MLP, které bylo původně v souboru OptimizeMLP. Dosahuje to úspěšnosti mezi 60-70 %

**Comment by bombic94** [comment]
algoritmy pro extrakci příznaků jsou s defaultníma parametrama (nevím přesně hodnoty, jsou uloženy v txt souborech). S těma jsme si nehráli ani to nebylo úkolem. Nevhodný si nepamatuju ale dá se říct že nejvhodnější počet neuronů skryté sítě je v rozmezí 50-80% vstupních dat (48 dat, ideálně bylo 24-40 neuronů)
Jojo máme porovnávat s MLP a možná připsat jestli je někde ta úspěšnost těch klasifikátorů ve složce new_models

**Comment by bombic94** [comment]
Nahrány všechny natrénované klasifikátory a pomocné soubory do složky data/test_classifiers_and_settings. Natrénováno dle nejlepších parametrů na základě testování úspěšnosti. Mělo by fungovat pro klasifikaci souborů, nedokážu otestovat Test all datasets, zmrzne mi Eclipse

**Comment by Sedmikras** [comment]
Test all datasets vyřeší zadavatel za stržení bodu. Otestováno, optimalizováno.
